### ISSUE TITLE
Would be awesome if there would be somekind of demo page

### ISSUE THREAD

**Issue by commwork** [pyrsmk/vertical-rhythmic#5]
I don't know if I am doing this all the right way so a demo page or a little bit more info would be awesome :)

**Comment by pyrsmk** [comment]
Good idea! I think I'll create a demo page with simple EM typography, a vertical-rhythmic one, and a modular-scale one.

**Comment by commwork** [comment]
hi pyrsmk, that would be awesome because I think this is a good way to get vertical rythm without headches.

**Comment by pyrsmk** [comment]
In fact, you just need to establish the baseline with `vr-baseline()` and then call `vr()` at each place where you need to apply a rhythm. The first parameter is the current font size of your block (so, the font size of the block itself or the font size of its parent), and second is a factor which will be based on our base rhythm.

So `margin: vr(1.6rem, 2) 0;` will create a `margin-top` and a `margin-bottom` based on twice your rhythm, for a font size of `1.6rem`. To choose what factor to use, you'll need to test by yourself when your factor is too small or too wide.

Generally, vertical rhythm will be applied to : 

- line-height
- margins
- paddings

Another thing : in the docs, don't take attention to chapters V and VI, they're not needed

I hope it clarifies you some things, until the demo page is released ;)

**Comment by commwork** [comment]
Thanks for the reply. If I understand this right I did it exactly this way. I'll take a look again when I am back home. I think I just couldn't believe it's that easy ... hmm.

**Comment by pyrsmk** [comment]
Hi! Did you manage to use the library as you want?
Sorry for the time I take to release a demo page, there's a lot of projects I'm working on ;)

**Comment by commwork** [comment]
hello pyrsmk, I had no more time to work on this project but next week, can't wait to check it out, want to insert it into my responsive mixin.

**Comment by pyrsmk** [comment]
No problem, keep in touch ;)

**Comment by Madebym** [comment]
@pyrsmk Any chance of throwing a quick Codepen demo that uses your library with Sass Modular Scale?

That would be pretty awesome :)

**Comment by pyrsmk** [comment]
In fact, there's many things I need to think and clarify to see how to handle modular-scale and vertical-rhythmic. Because modular-scale is based on a specific ratio, contrary to vertical-rhythmic which is based on a repetition of a size. Using the both in cunjunction would lose the benefits of a modular scale. Maybe.

**Comment by pyrsmk** [comment]
I'm currently writing the example page that will compare vertical-rhythmic and modular-scale ;)

**Comment by pyrsmk** [comment]
http://codepen.io/pyrsmk/full/PNeJgg/

So! We have a comparison between three layouts. The first is with vertical-rhythmic only. The second with modular-scale. And the third with both. The example is really simple, but is enough for now.

As you may see : 

- the first example doesn't feel equilibrated in term of spacing/proportions
- the second is more equilibrated, but modular-scale doesn't simply allow to use grained sizes, so we have big gaps in font sizes
- the third has the best results

**Comment by Madebym** [comment]
@pyrsmk Big thanks for the examples. The third one is the one I need. 

+1 for Batman :)

**Comment by pyrsmk** [comment]
Great, I'm glad that helped!

**Comment by pyrsmk** [comment]
Also, I clarified the docs about modular scale use ;)
