### ISSUE TITLE
Add !default to $vr-ratio

### ISSUE THREAD

**Issue by designermonkey** [pyrsmk/vertical-rhythmic#6]
Setting this as a default parameter also allows users to just define this in their config, and not have to use the `vr-baseline` mixin.

Without this, and going based on the readme, even declaring the scale factor to `vr`, I get this:

```
Invalid null operation: "null times 1". 
```

If `$vr-ratio` isn't set ever, then sass compilation fails.

I guess it should be `0` rather than `null` as a default, so

```
$vr-ratio: 0 !default;
```

**Comment by pyrsmk** [comment]
Using `vr-baseline` mixin is needed since it sets the `$vr-ratio`, and it should not be set anywhere else (that's why I put a `!global` on it).

**Comment by pyrsmk** [comment]
I'll make some tests ASAP ;)

**Comment by pyrsmk** [comment]
I'm working on a new version of the library that will be based on your advices.

**Comment by designermonkey** [comment]
Awesome! Thanks.
